apiVersion: v1
kind: ConfigMap
metadata:
  name: {{include "maddy.fullname" .}}
  labels: {{- include "maddy.labels" . | nindent 4}}
data:
  maddy.conf: |
{{ .Values.config | indent 4 }}
  aliases: |
{{ .Values.aliases | indent 4 }}
  users: |
{{ .Values.users | indent 4 }}
